version: '3.8'
services:
  email-service-1:
    build: .
    container_name: email-service-1
    ports:
      - '3001:3000'

  email-service-2:
    build: .
    container_name: email-service-2
    ports:
      - '3002:3000'

  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - email-service-1
      - email-service-2

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - email-service-1
      - email-service-2

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
